In [2]:
import numpy as np 
import pandas as pd

In [4]:
df=pd.read_excel(r'C:\Users\adisa\Downloads\Final scraped data.xlsx')

In [5]:
df.head(2)

,restaurant_id,Name,Ratings,Price_for_one,cusines,Restaurant_link,location,Longitude,Latitute,delivery_review_number
0,0,Bakingo,4.3,300,"Bakery, Desserts",https: //www.zomato.com/bangalore/bakingo-vasa...,"Vasanth Nagar, Bangalore",77.585169,12.988721,0
1,1,Empire Restaurant,4.1,300,"North Indian, Biryani, Kebab, Chinese, South I...",https: //www.zomato.com/bangalore/empire-resta...,"Shivajinagar, Bangalore",77.607542,12.986391,4847

In [6]:
df['cusines'].replace(" ", '', regex=True, inplace=True)

In [7]:
new = df['cusines'].str.split(',', expand=True)

In [8]:
new

,0,1,2,3,4,5,6,7
0,Bakery,Desserts,None,None,None,None,None,None
1,NorthIndian,Biryani,Kebab,Chinese,SouthIndian,Mughlai,Beverages,None
2,NorthIndian,Biryani,Sichuan,StreetFood,Chinese,None,None,None
3,IceCream,Bakery,Desserts,None,None,None,None,None
4,Burger,FastFood,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...
676,Bakery,Desserts,None,None,None,None,None,None
677,NorthIndian,Rolls,None,None,None,None,None,None
678,Mithai,StreetFood,FastFood,None,None,None,None,None
679,NorthIndian,None,None,None,None,None,None,None
680,Paan,Desserts,None,None,None,None,None,None

In [9]:
df['cusines'].nunique()

521

In [10]:
from keras.preprocessing.text import Tokenizer

In [11]:
t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(df['cusines'])
# summarize what was learned
dic = t.word_index

In [12]:
encoded_docs = t.texts_to_matrix(df['cusines'], mode='count')
print(encoded_docs)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [13]:
dic

{'northindian': 1,
 'chinese': 2,
 'beverages': 3,
 'desserts': 4,
 'biryani': 5,
 'southindian': 6,
 'fastfood': 7,
 'streetfood': 8,
 'mughlai': 9,
 'sichuan': 10,
 'shake': 11,
 'icecream': 12,
 'seafood': 13,
 'rolls': 14,
 'pizza': 15,
 'burger': 16,
 'bakery': 17,
 'kebab': 18,
 'andhra': 19,
 'sandwich': 20,
 'juices': 21,
 'momos': 22,
 'arabian': 23,
 'italian': 24,
 'kerala': 25,
 'mithai': 26,
 'asian': 27,
 'thai': 28,
 'continental': 29,
 'lebanese': 30,
 'hyderabadi': 31,
 'pasta': 32,
 'healthyfood': 33,
 'salad': 34,
 'wraps': 35,
 'cafe': 36,
 'bengali': 37,
 'mangalorean': 38,
 'mexican': 39,
 'waffle': 40,
 'japanese': 41,
 'bbq': 42,
 'tea': 43,
 'rajasthani': 44,
 'coffee': 45,
 'sushi': 46,
 'american': 47,
 'chettinad': 48,
 'oriental': 49,
 'tibetan': 50,
 'maharashtrian': 51,
 'vietnamese': 52,
 'korean': 53,
 'shawarma': 54,
 'odia': 55,
 'lucknowi': 56,
 'afghan': 57,
 'malaysian': 58,
 'barfood': 59,
 'indonesian': 60,
 'european': 61,
 'awadhi': 62,
 'paan': 63,
 'pancake': 64,
 'modernindian': 65,
 'burmese': 66,
 'gujarati': 67,
 'fingerfood': 68,
 'french': 69,
 'panini': 70,
 'middleeastern': 71,
 'portuguese': 72,
 'parsi': 73,
 'singaporean': 74,
 'mishti': 75}

In [14]:
new_dict = dict([(value, key) for key, value in dic.items()])
new_dict

{1: 'northindian',
 2: 'chinese',
 3: 'beverages',
 4: 'desserts',
 5: 'biryani',
 6: 'southindian',
 7: 'fastfood',
 8: 'streetfood',
 9: 'mughlai',
 10: 'sichuan',
 11: 'shake',
 12: 'icecream',
 13: 'seafood',
 14: 'rolls',
 15: 'pizza',
 16: 'burger',
 17: 'bakery',
 18: 'kebab',
 19: 'andhra',
 20: 'sandwich',
 21: 'juices',
 22: 'momos',
 23: 'arabian',
 24: 'italian',
 25: 'kerala',
 26: 'mithai',
 27: 'asian',
 28: 'thai',
 29: 'continental',
 30: 'lebanese',
 31: 'hyderabadi',
 32: 'pasta',
 33: 'healthyfood',
 34: 'salad',
 35: 'wraps',
 36: 'cafe',
 37: 'bengali',
 38: 'mangalorean',
 39: 'mexican',
 40: 'waffle',
 41: 'japanese',
 42: 'bbq',
 43: 'tea',
 44: 'rajasthani',
 45: 'coffee',
 46: 'sushi',
 47: 'american',
 48: 'chettinad',
 49: 'oriental',
 50: 'tibetan',
 51: 'maharashtrian',
 52: 'vietnamese',
 53: 'korean',
 54: 'shawarma',
 55: 'odia',
 56: 'lucknowi',
 57: 'afghan',
 58: 'malaysian',
 59: 'barfood',
 60: 'indonesian',
 61: 'european',
 62: 'awadhi',
 63: 'paan',
 64: 'pancake',
 65: 'modernindian',
 66: 'burmese',
 67: 'gujarati',
 68: 'fingerfood',
 69: 'french',
 70: 'panini',
 71: 'middleeastern',
 72: 'portuguese',
 73: 'parsi',
 74: 'singaporean',
 75: 'mishti'}

In [15]:
df1 = pd.DataFrame(encoded_docs)
df1

,0,1,2,3,4,5,6,7,8,9,...,66,67,68,69,70,71,72,73,74,75
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
677,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df1.rename(columns ={1: 'northindian',
 2: 'chinese',
 3: 'beverages',
 4: 'desserts',
 5: 'biryani',
 6: 'southindian',
 7: 'fastfood',
 8: 'streetfood',
 9: 'mughlai',
 10: 'sichuan',
 11: 'shake',
 12: 'icecream',
 13: 'seafood',
 14: 'rolls',
 15: 'pizza',
 16: 'burger',
 17: 'bakery',
 18: 'kebab',
 19: 'andhra',
 20: 'sandwich',
 21: 'juices',
 22: 'momos',
 23: 'arabian',
 24: 'italian',
 25: 'kerala',
 26: 'mithai',
 27: 'asian',
 28: 'thai',
 29: 'continental',
 30: 'lebanese',
 31: 'hyderabadi',
 32: 'pasta',
 33: 'healthyfood',
 34: 'salad',
 35: 'wraps',
 36: 'cafe',
 37: 'bengali',
 38: 'mangalorean',
 39: 'mexican',
 40: 'waffle',
 41: 'japanese',
 42: 'bbq',
 43: 'tea',
 44: 'rajasthani',
 45: 'coffee',
 46: 'sushi',
 47: 'american',
 48: 'chettinad',
 49: 'oriental',
 50: 'tibetan',
 51: 'maharashtrian',
 52: 'vietnamese',
 53: 'korean',
 54: 'shawarma',
 55: 'odia',
 56: 'lucknowi',
 57: 'afghan',
 58: 'malaysian',
 59: 'barfood',
 60: 'indonesian',
 61: 'european',
 62: 'awadhi',
 63: 'paan',
 64: 'pancake',
 65: 'modernindian',
 66: 'burmese',
 67: 'gujarati',
 68: 'fingerfood',
 69: 'french',
 70: 'panini',
 71: 'middleeastern',
 72: 'portuguese',
 73: 'parsi',
 74: 'singaporean',
 75: 'mishti'},inplace=True)

In [17]:
df1.drop(0,axis=1,inplace=True)

In [18]:
df2 = df.join(df1)
df2

,restaurant_id,Name,Ratings,Price_for_one,cusines,Restaurant_link,location,Longitude,Latitute,delivery_review_number,...,burmese,gujarati,fingerfood,french,panini,middleeastern,portuguese,parsi,singaporean,mishti
0,0,Bakingo,4.3,300,"Bakery,Desserts",https: //www.zomato.com/bangalore/bakingo-vasa...,"Vasanth Nagar, Bangalore",77.585169,12.988721,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,Empire Restaurant,4.1,300,"NorthIndian,Biryani,Kebab,Chinese,SouthIndian,...",https: //www.zomato.com/bangalore/empire-resta...,"Shivajinagar, Bangalore",77.607542,12.986391,4847,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Flavors Of North,3.8,300,"NorthIndian,Biryani,Sichuan,StreetFood,Chinese",https: //www.zomato.com/bangalore/flavors-of-n...,"Rajajinagar, Bangalore",77.554883,12.988234,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,ibaco,4.5,300,"IceCream,Bakery,Desserts",https: //www.zomato.com/bangalore/ibaco-brigad...,"Brigade Road, Bangalore",77.606966,12.971485,107,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,McDonald's,4.0,300,"Burger,FastFood",https: //www.zomato.com/bangalore/mcdonalds-mg...,"MG Road, Bangalore",77.606790,12.975526,212,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,676,Sweet Bake - Cake And Desserts,0.0,250,"Bakery,Desserts",https: //www.zomato.com/bangalore/sweet-bake-c...,"Koramangala 7th Block, Bangalore",77.613478,12.936485,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
677,677,Rosy Roti,4.1,250,"NorthIndian,Rolls",https: //www.zomato.com/bangalore/rosy-roti-do...,"Domlur, Bangalore",77.638196,12.962467,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
678,678,Svadu Pure Ghee Sweets,3.4,250,"Mithai,StreetFood,FastFood",https: //www.zomato.com/bangalore/svadu-pure-g...,"BTM, Bangalore",77.604565,12.911276,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
679,679,Uncle Tom's Cafe,3.6,250,NorthIndian,https: //www.zomato.com/bangalore/uncle-toms-c...,"Basaveshwara Nagar, Bangalore",77.539475,12.993161,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
680,680,The Betel Leaf Co - Originally from Bangalore,4.4,250,"Paan,Desserts",https: //www.zomato.com/bangalore/the-betel-le...,"Seshadripuram, Bangalore",77.575342,12.993188,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df2.drop(columns = ['restaurant_id','Name','Longitude','Latitute','Restaurant_link','cusines','delivery_review_number'],inplace= True)

In [20]:
df2

,Ratings,Price_for_one,location,northindian,chinese,beverages,desserts,biryani,southindian,fastfood,...,burmese,gujarati,fingerfood,french,panini,middleeastern,portuguese,parsi,singaporean,mishti
0,4.3,300,"Vasanth Nagar, Bangalore",0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.1,300,"Shivajinagar, Bangalore",1.0,1.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.8,300,"Rajajinagar, Bangalore",1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.5,300,"Brigade Road, Bangalore",0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.0,300,"MG Road, Bangalore",0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,0.0,250,"Koramangala 7th Block, Bangalore",0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
677,4.1,250,"Domlur, Bangalore",1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
678,3.4,250,"BTM, Bangalore",0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
679,3.6,250,"Basaveshwara Nagar, Bangalore",1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
680,4.4,250,"Seshadripuram, Bangalore",0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
df2.drop(columns = ['Ratings'], inplace= True)

In [22]:
pt=df2.set_index('location')

In [23]:
pt

,Price_for_one,northindian,chinese,beverages,desserts,biryani,southindian,fastfood,streetfood,mughlai,...,burmese,gujarati,fingerfood,french,panini,middleeastern,portuguese,parsi,singaporean,mishti
location,,,,,,,,,,,,,,,,,,,,,
"Vasanth Nagar, Bangalore",300,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Shivajinagar, Bangalore",300,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Rajajinagar, Bangalore",300,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Brigade Road, Bangalore",300,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"MG Road, Bangalore",300,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Koramangala 7th Block, Bangalore",250,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Domlur, Bangalore",250,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"BTM, Bangalore",250,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Basaveshwara Nagar, Bangalore",250,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Seshadripuram, Bangalore",250,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity_scores = cosine_similarity(pt)

In [26]:
similarity_scores

array([[1.        , 0.99995   , 0.99996111, ..., 0.99996489, 0.99998089,
        0.99998622],
       [0.99995   , 1.        , 0.99996667, ..., 0.99993712, 0.99996645,
        0.99994511],
       [0.99996111, 0.99996667, 1.        , ..., 0.99996156, 0.99997756,
        0.99995622],
       ...,
       [0.99996489, 0.99993712, 0.99996156, ..., 1.        , 0.999968  ,
        0.99996   ],
       [0.99998089, 0.99996645, 0.99997756, ..., 0.999968  , 1.        ,
        0.999976  ],
       [0.99998622, 0.99994511, 0.99995622, ..., 0.99996   , 0.999976  ,
        1.        ]])

In [27]:
def recommend(location_name):
    index=np.where(pt.index==location_name)[0][0]
    similar_location=sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:2]
    for i in similar_location:
        print(pt.index[i[0]])

In [28]:
recommend('Seshadripuram, Bangalore')

Jayanagar, Bangalore

In [29]:
sorted(list(enumerate(similarity_scores[0])),key=lambda x:x[1],reverse=True)

[(0, 1.0),
 (401, 1.0),
 (334, 0.9999995555795547),
 (432, 0.9999995555795547),
 (499, 0.9999995555795547),
 (673, 0.9999995555795547),
 (676, 0.9999995555795547),
 (242, 0.9999993055794265),
 (247, 0.9999993055794265),
 (272, 0.9999972224189707),
 (356, 0.9999972224189707),
 (610, 0.9999972224189707),
 (3, 0.9999944446141922),
 (57, 0.9999944446141922),
 (671, 0.9999942223374793),
 (246, 0.9999940973381416),
 (477, 0.9999915559350943),
 (487, 0.9999915559350943),
 (490, 0.9999915559350943),
 (319, 0.9999915557084417),
 (320, 0.9999915557084417),
 (244, 0.9999909723907665),
 (245, 0.9999899308349531),
 (315, 0.9999895557473297),
 (144, 0.9999888900616264),
 (219, 0.9999888900616264),
 (226, 0.9999888900616264),
 (229, 0.9999888900616264),
 (234, 0.9999888900616264),
 (235, 0.9999888900616264),
 (275, 0.9999888893209706),
 (278, 0.9999888893209706),
 (397, 0.9999888891357971),
 (311, 0.9999868891022925),
 (317, 0.9999868891022925),
 (680, 0.9999862226076929),
 (310, 0.9999855558611047),
 (313, 0.999984889142514),
 (47, 0.9999848075117574),
 (237, 0.9999847225839036),
 (61, 0.9999833338117143),
 (65, 0.9999833338117143),
 (398, 0.9999833336265379),
 (403, 0.9999833336265379),
 (422, 0.9999833336265379),
 (553, 0.9999833336265379),
 (557, 0.9999833336265379),
 (240, 0.9999826392021065),
 (238, 0.9999815977244146),
 (239, 0.9999815977244146),
 (309, 0.999981556022877),
 (312, 0.9999808892589558),
 (318, 0.9999808892589558),
 (437, 0.9999808892589558),
 (468, 0.9999808892589558),
 (482, 0.9999808892589558),
 (492, 0.9999808892589558),
 (540, 0.9999808892589558),
 (548, 0.9999808892589558),
 (679, 0.9999808892589558),
 (56, 0.9999807259994219),
 (34, 0.9999805563541325),
 (316, 0.999979556121762),
 (241, 0.999979514310068),
 (430, 0.9999782230698915),
 (471, 0.9999782230698915),
 (498, 0.9999782230698915),
 (547, 0.9999782230698915),
 (421, 0.9999777785802169),
 (4, 0.9999777782715941),
 (67, 0.9999777782715941),
 (417, 0.9999777782715941),
 (423, 0.9999777782715941),
 (426, 0.9999777782715941),
 (427, 0.9999777782715941),
 (551, 0.9999777782715941),
 (559, 0.9999777782715941),
 (314, 0.9999768894233951),
 (45, 0.9999766445370627),
 (52, 0.9999766445370627),
 (133, 0.9999763894473248),
 (183, 0.9999763894473248),
 (261, 0.9999763894473248),
 (262, 0.9999763894473248),
 (265, 0.9999763894473248),
 (294, 0.9999763894473248),
 (349, 0.9999763894473248),
 (454, 0.9999763894473248),
 (615, 0.9999763894473248),
 (617, 0.9999763894473248),
 (660, 0.9999763894473248),
 (665, 0.9999763894473248),
 (248, 0.9999753480933202),
 (434, 0.9999728896358311),
 (474, 0.9999728896358311),
 (481, 0.9999728896358311),
 (484, 0.9999728896358311),
 (486, 0.9999728896358311),
 (488, 0.9999728896358311),
 (489, 0.9999728896358311),
 (494, 0.9999728896358311),
 (496, 0.9999728896358311),
 (599, 0.9999728896358311),
 (606, 0.9999728896358311),
 (677, 0.9999728896358311),
 (89, 0.9999722246757089),
 (306, 0.9999722246757089),
 (413, 0.9999722246757089),
 (8, 0.9999722234413014),
 (68, 0.9999722234413014),
 (549, 0.9999722234413014),
 (58, 0.9999722230092365),
 (59, 0.9999722230092365),
 (62, 0.9999722230092365),
 (64, 0.9999722230092365),
 (400, 0.9999722230092365),
 (402, 0.9999722230092365),
 (404, 0.9999722230092365),
 (420, 0.9999722230092365),
 (428, 0.9999722230092365),
 (550, 0.9999722230092365),
 (479, 0.9999702237240676),
 (544, 0.9999702237240676),
 (243, 0.9999701398097219),
 (50, 0.9999698426189834),
 (48, 0.9999684817622704),
 (51, 0.9999684817622704),
 (53, 0.9999684817622704),
 (54, 0.9999684817622704),
 (134, 0.9999680574564769),
 (613, 0.9999680574564769),
 (107, 0.9999666690738911),
 (147, 0.9999666690738911),
 (359, 0.9999666690738911),
 (379, 0.9999666690738911),
 (6, 0.9999666683949657),
 (399, 0.9999666683949657),
 (60, 0.9999666678394631),
 (111, 0.9999666678394631),
 (149, 0.9999666678394631),
 (163, 0.9999666678394631),
 (220, 0.9999666678394631),
 (228, 0.9999666678394631),
 (250, 0.9999666678394631),
 (254, 0.9999666678394631),
 (361, 0.9999666678394631),
 (393, 0.9999666678394631),
 (418, 0.9999666678394631),
 (516, 0.9999666678394631),
 (554, 0.9999666678394631),
 (631, 0.9999666678394631),
 (632, 0.9999666678394631),
 (431, 0.9999648902046887),
 (433, 0.9999648902046887),
 (465, 0.9999648902046887),
 (472, 0.9999648902046887),
 (478, 0.9999648902046887),
 (480, 0.9999648902046887),
 (500, 0.9999648902046887),
 (537, 0.9999648902046887),
 (539, 0.9999648902046887),
 (598, 0.9999648902046887),
 (607, 0.9999648902046887),
 (669, 0.9999648902046887),
 (670, 0.9999648902046887),
 (672, 0.9999648902046887),
 (674, 0.9999648902046887),
 (678, 0.9999648902046887),
 (46, 0.9999644004498351),
 (49, 0.9999644004498351),
 (55, 0.9999644004498351),
 (33, 0.9999638902892943),
 (38, 0.9999638902892943),
 (139, 0.9999638902892943),
 (177, 0.9999638902892943),
 (187, 0.9999638902892943),
 (269, 0.9999638902892943),
 (290, 0.9999638902892943),
 (291, 0.9999638902892943),
 (345, 0.9999638902892943),
 (346, 0.9999638902892943),
 (348, 0.9999638902892943),
 (350, 0.9999638902892943),
 (456, 0.9999638902892943),
 (457, 0.9999638902892943),
 (458, 0.9999638902892943),
 (461, 0.9999638902892943),
 (611, 0.9999638902892943),
 (618, 0.9999638902892943),
 (619, 0.9999638902892943),
 (620, 0.9999638902892943),
 (657, 0.9999638902892943),
 (333, 0.9999622245702134),
 (338, 0.9999622245702134),
 (341, 0.9999622245702134),
 (343, 0.9999622245702134),
 (429, 0.9999622245702134),
 (440, 0.9999622245702134),
 (66, 0.9999611134412074),
 (2, 0.9999611127622707),
 (63, 0.9999611127622707),
 (395, 0.9999611127622707),
 (425, 0.9999611127622707),
 (560, 0.9999611127622707),
 (336, 0.9999568909655214),
 (438, 0.9999568909655214),
 (439, 0.9999568909655214),
 (483, 0.9999568909655214),
 (497, 0.9999568909655214),
 (543, 0.9999568909655214),
 (545, 0.9999568909655214),
 (603, 0.9999568909655214),
 (501, 0.9999555644428425),
 (129, 0.9999555590274859),
 (267, 0.9999555590274859),
 (286, 0.9999555590274859),
 (612, 0.9999555590274859),
 (662, 0.9999555590274859),
 (5, 0.9999555585800234),
 (7, 0.9999555585800234),
 (555, 0.9999555585800234),
 (556, 0.9999555585800234),
 (558, 0.9999555585800234),
 (396, 0.9999555577776571),
 (424, 0.9999555577776571),
 (552, 0.9999555577776571),
 (337, 0.9999542256083211),
 (342, 0.9999542256083211),
 (435, 0.9999542256083211),
 (467, 0.9999542256083211),
 (475, 0.9999542256083211),
 (491, 0.9999542256083211),
 (601, 0.9999542256083211),
 (675, 0.9999542256083211),
 (37, 0.9999513915999502),
 (42, 0.9999513915999502),
 (180, 0.9999513915999502),
 (182, 0.9999513915999502),
 (184, 0.9999513915999502),
 (185, 0.9999513915999502),
 (188, 0.9999513915999502),
 (266, 0.9999513915999502),
 (287, 0.9999513915999502),
 (355, 0.9999513915999502),
 (460, 0.9999513915999502),
 (614, 0.9999513915999502),
 (658, 0.9999513915999502),
 (1, 0.9999500028856197),
 (394, 0.9999500028856197),
 (339, 0.9999488919183211),
 (340, 0.9999488919183211),
 (466, 0.9999488919183211),
 (470, 0.9999488919183211),
 (476, 0.9999488919183211),
 (485, 0.9999488919183211),
 (493, 0.9999488919183211),
 (546, 0.9999488919183211),
 (597, 0.9999488919183211),
 (602, 0.9999488919183211),
 (608, 0.9999488919183211),
 (335, 0.9999462268383833),
 (436, 0.9999462268383833),
 (541, 0.9999462268383833),
 (600, 0.9999462268383833),
 (222, 0.9999444503079803),
 (143, 0.9999444480861558),
 (148, 0.9999444480861558),
 (156, 0.9999444480861558),
 (159, 0.9999444480861558),
 (160, 0.9999444480861558),
 (161, 0.9999444480861558),
 (162, 0.9999444480861558),
 (215, 0.9999444480861558),
 (223, 0.9999444480861558),
 (225, 0.9999444480861558),
 (256, 0.9999444480861558),
 (257, 0.9999444480861558),
 (259, 0.9999444480861558),
 (277, 0.9999444480861558),
 (367, 0.9999444480861558),
 (369, 0.9999444480861558),
 (371, 0.9999444480861558),
 (377, 0.9999444480861558),
 (419, 0.9999444480861558),
 (513, 0.9999444480861558),
 (515, 0.9999444480861558),
 (517, 0.9999444480861558),
 (522, 0.9999444480861558),
 (523, 0.9999444480861558),
 (524, 0.9999444480861558),
 (586, 0.9999444480861558),
 (591, 0.9999444480861558),
 (592, 0.9999444480861558),
 (594, 0.9999444480861558),
 (626, 0.9999444480861558),
 (630, 0.9999444480861558),
 (35, 0.9999430610671303),
 (178, 0.9999430610671303),
 (186, 0.9999430610671303),
 (296, 0.9999430610671303),
 (661, 0.9999430610671303),
 (495, 0.9999408930630803),
 (604, 0.9999408930630803),
 (81, 0.9999388933792629),
 (123, 0.9999388933792629),
 (131, 0.9999388933792629),
 (135, 0.9999388933792629),
 (136, 0.9999388933792629),
 (140, 0.9999388933792629),
 (174, 0.9999388933792629),
 (271, 0.9999388933792629),
 (289, 0.9999388933792629),
 (301, 0.9999388933792629),
 (302, 0.9999388933792629),
 (307, 0.9999388933792629),
 (308, 0.9999388933792629),
 (351, 0.9999388933792629),
 (352, 0.9999388933792629),
 (353, 0.9999388933792629),
 (447, 0.9999388933792629),
 (449, 0.9999388933792629),
 (453, 0.9999388933792629),
 (503, 0.9999388933792629),
 (504, 0.9999388933792629),
 (505, 0.9999388933792629),
 (511, 0.9999388933792629),
 (533, 0.9999388933792629),
 (609, 0.9999388933792629),
 (633, 0.9999388933792629),
 (659, 0.9999388933792629),
 (666, 0.9999388933792629),
 (344, 0.9999328943997913),
 (538, 0.9999328943997913),
 (542, 0.9999328943997913),
 (41, 0.9999305635753809),
 (132, 0.9999305635753809),
 (138, 0.9999305635753809),
 (179, 0.9999305635753809),
 (181, 0.9999305635753809),
 (293, 0.9999305635753809),
 (295, 0.9999305635753809),
 (616, 0.9999305635753809),
 (137, 0.9999263956272032),
 (285, 0.9999263956272032),
 (354, 0.9999263956272032),
 (462, 0.9999263956272032),
 (463, 0.9999263956272032),
 (663, 0.9999263956272032),
 (667, 0.9999263956272032),
 (668, 0.9999263956272032),
 (469, 0.9999248959284464),
 (473, 0.9999248959284464),
 (605, 0.9999248959284464),
 (70, 0.9999222348126697),
 (567, 0.9999222348126697),
 (640, 0.9999222348126697),
 (13, 0.9999222330230737),
 (14, 0.9999222330230737),
 (105, 0.9999222330230737),
 (213, 0.9999222330230737),
 (214, 0.9999222330230737),
 (224, 0.9999222330230737),
 (283, 0.9999222330230737),
 (518, 0.9999222330230737),
 (588, 0.9999222330230737),
 (646, 0.9999222330230737),
 (11, 0.9999222298139844),
 (12, 0.9999222298139844),
 (19, 0.9999222298139844),
 (98, 0.9999222298139844),
 (106, 0.9999222298139844),
 (109, 0.9999222298139844),
 (114, 0.9999222298139844),
 (150, 0.9999222298139844),
 (154, 0.9999222298139844),
 (158, 0.9999222298139844),
 (164, 0.9999222298139844),
 (230, 0.9999222298139844),
 (249, 0.9999222298139844),
 (251, 0.9999222298139844),
 (273, 0.9999222298139844),
 (364, 0.9999222298139844),
 (366, 0.9999222298139844),
 (376, 0.9999222298139844),
 (514, 0.9999222298139844),
 (521, 0.9999222298139844),
 (585, 0.9999222298139844),
 (593, 0.9999222298139844),
 (621, 0.9999222298139844),
 (628, 0.9999222298139844),
 (645, 0.9999222298139844),
 (652, 0.9999222298139844),
 (654, 0.9999222298139844),
 (459, 0.9999180665522085),
 (40, 0.9999138983437419),
 (43, 0.9999138983437419),
 (268, 0.9999138983437419),
 (270, 0.9999138983437419),
 (288, 0.9999138983437419),
 (455, 0.9999138983437419),
 (464, 0.9999138983437419),
 (118, 0.9999055804101982),
 (130, 0.9999055699975833),
 (264, 0.9999055699975833),
 (263, 0.9999014015288497),
 (292, 0.9999014015288497),
 (664, 0.9999014015288497),
 (374, 0.9999000219085904),
 (108, 0.9999000172190068),
 (357, 0.9999000172190068),
 (358, 0.9999000172190068),
 (373, 0.9999000172190068),
 (378, 0.9999000172190068),
 (622, 0.9999000172190068),
 (10, 0.9999000130227843),
 (95, 0.9999000130227843),
 (116, 0.9999000130227843),
 (142, 0.9999000130227843),
 (152, 0.9999000130227843),
 (153, 0.9999000130227843),
 (155, 0.9999000130227843),
 (157, 0.9999000130227843),
 (216, 0.9999000130227843),
 (218, 0.9999000130227843),
 (253, 0.9999000130227843),
 (255, 0.9999000130227843),
 (274, 0.9999000130227843),
 (280, 0.9999000130227843),
 (281, 0.9999000130227843),
 (360, 0.9999000130227843),
 (375, 0.9999000130227843),
 (623, 0.9999000130227843),
 (624, 0.9999000130227843),
 (629, 0.9999000130227843),
 (648, 0.9999000130227843),
 (653, 0.9999000130227843),
 (656, 0.9999000130227843),
 (23, 0.999888905182497),
 (24, 0.999888905182497),
 (36, 0.999888905182497),
 (39, 0.999888905182497),
 (44, 0.999888905182497),
 (82, 0.999888905182497),
 (119, 0.999888905182497),
 (121, 0.999888905182497),
 (169, 0.999888905182497),
 (170, 0.999888905182497),
 (172, 0.999888905182497),
 (175, 0.999888905182497),
 (176, 0.999888905182497),
 (205, 0.999888905182497),
 (206, 0.999888905182497),
 (211, 0.999888905182497),
 (303, 0.999888905182497),
 (323, 0.999888905182497),
 (327, 0.999888905182497),
 (331, 0.999888905182497),
 (332, 0.999888905182497),
 (347, 0.999888905182497),
 (382, 0.999888905182497),
 (384, 0.999888905182497),
 (411, 0.999888905182497),
 (441, 0.999888905182497),
 (442, 0.999888905182497),
 (445, 0.999888905182497),
 (452, 0.999888905182497),
 (502, 0.999888905182497),
 (531, 0.999888905182497),
 (535, 0.999888905182497),
 (571, 0.999888905182497),
 (634, 0.999888905182497),
 (635, 0.999888905182497),
 (637, 0.999888905182497),
 (642, 0.999888905182497),
 (115, 0.9998778085721018),
 (104, 0.9998778028956152),
 (151, 0.9998778028956152),
 (236, 0.9998778028956152),
 (17, 0.9998777977123909),
 (103, 0.9998777977123909),
 (260, 0.9998777977123909),
 (276, 0.9998777977123909),
 (284, 0.9998777977123909),
 (362, 0.9998777977123909),
 (363, 0.9998777977123909),
 (520, 0.9998777977123909),
 (596, 0.9998777977123909),
 (625, 0.9998777977123909),
 (650, 0.9998777977123909),
 (651, 0.9998777977123909),
 (655, 0.9998777977123909),
 (27, 0.9998722524460488),
 (412, 0.9998722524460488),
 (16, 0.9998555900527344),
 (96, 0.9998555900527344),
 (99, 0.9998555900527344),
 (141, 0.9998555900527344),
 (227, 0.9998555900527344),
 (252, 0.9998555900527344),
 (279, 0.9998555900527344),
 (282, 0.9998555900527344),
 (380, 0.9998555900527344),
 (589, 0.9998555900527344),
 (20, 0.9998555838826401),
 (94, 0.9998555838826401),
 (101, 0.9998555838826401),
 (112, 0.9998555838826401),
 (146, 0.9998555838826401),
 (233, 0.9998555838826401),
 (370, 0.9998555838826401),
 (587, 0.9998555838826401),
 (590, 0.9998555838826401),
 (595, 0.9998555838826401),
 (627, 0.9998555838826401),
 (649, 0.9998555838826401),
 (21, 0.9998389244818995),
 (26, 0.9998389244818995),
 (77, 0.9998389244818995),
 (79, 0.9998389244818995),
 (80, 0.9998389244818995),
 (84, 0.9998389244818995),
 (86, 0.9998389244818995),
 (87, 0.9998389244818995),
 (90, 0.9998389244818995),
 (128, 0.9998389244818995),
 (165, 0.9998389244818995),
 (166, 0.9998389244818995),
 (167, 0.9998389244818995),
 (173, 0.9998389244818995),
 (210, 0.9998389244818995),
 (297, 0.9998389244818995),
 (324, 0.9998389244818995),
 (329, 0.9998389244818995),
 (385, 0.9998389244818995),
 (409, 0.9998389244818995),
 (450, 0.9998389244818995),
 (506, 0.9998389244818995),
 (508, 0.9998389244818995),
 (510, 0.9998389244818995),
 (562, 0.9998389244818995),
 (563, 0.9998389244818995),
 (564, 0.9998389244818995),
 (565, 0.9998389244818995),
 (566, 0.9998389244818995),
 (9, 0.9998333786901997),
 (15, 0.9998333786901997),
 (97, 0.9998333786901997),
 (100, 0.9998333786901997),
 (110, 0.9998333786901997),
 (113, 0.9998333786901997),
 (258, 0.9998333786901997),
 (519, 0.9998333786901997),
 (93, 0.9998333715333669),
 (102, 0.9998333715333669),
 (217, 0.9998333715333669),
 (221, 0.9998333715333669),
 (372, 0.9998333715333669),
 (25, 0.9998222775739724),
 (71, 0.9998222775739724),
 (209, 0.9998222775739724),
 (387, 0.9998222775739724),
 (389, 0.9998222775739724),
 (407, 0.9998222775739724),
 (444, 0.9998222775739724),
 (525, 0.9998222775739724),
 (528, 0.9998222775739724),
 (18, 0.9998111606644072),
 (145, 0.9998111606644072),
 (231, 0.9998111606644072),
 (232, 0.9998111606644072),
 (365, 0.9998111606644072),
 (368, 0.9998111606644072),
 (647, 0.9998111606644072),
 (638, 0.9998056348274199),
 (28, 0.9997889512755965),
 (75, 0.9997889512755965),
 (120, 0.9997889512755965),
 (126, 0.9997889512755965),
 (168, 0.9997889512755965),
 (198, 0.9997889512755965),
 (201, 0.9997889512755965),
 (208, 0.9997889512755965),
 (298, 0.9997889512755965),
 (321, 0.9997889512755965),
 (326, 0.9997889512755965),
 (383, 0.9997889512755965),
 (416, 0.9997889512755965),
 (443, 0.9997889512755965),
 (526, 0.9997889512755965),
 (580, 0.9997889512755965),
 (641, 0.9997889512755965),
 (643, 0.9997889512755965),
 (78, 0.9997723101945678),
 (325, 0.9997723101945678),
 (512, 0.9997723101945678),
 (530, 0.9997723101945678),
 (568, 0.9997723101945678),
 (85, 0.9997556732735406),
 (32, 0.9997389855617157),
 (125, 0.9997389855617157),
 (204, 0.9997389855617157),
 (328, 0.9997389855617157),
 (392, 0.9997389855617157),
 (405, 0.9997389855617157),
 (415, 0.9997389855617157),
 (448, 0.9997389855617157),
 (529, 0.9997389855617157),
 (534, 0.9997389855617157),
 (570, 0.9997389855617157),
 (636, 0.9997389855617157),
 (22, 0.9997223503059627),
 (72, 0.9997223503059627),
 (91, 0.9997223503059627),
 (202, 0.9997223503059627),
 (300, 0.9997223503059627),
 (406, 0.9997223503059627),
 (408, 0.9997223503059627),
 (507, 0.9997223503059627),
 (73, 0.9996890273383847),
 (117, 0.9996890273383847),
 (124, 0.9996890273383847),
 (322, 0.9996890273383847),
 (410, 0.9996890273383847),
 (446, 0.9996890273383847),
 (509, 0.9996890273383847),
 (527, 0.9996890273383847),
 (536, 0.9996890273383847),
 (561, 0.9996890273383847),
 (30, 0.999672397906286),
 (203, 0.999672397906286),
 (207, 0.999672397906286),
 (299, 0.999672397906286),
 (304, 0.999672397906286),
 (305, 0.999672397906286),
 (330, 0.999672397906286),
 (388, 0.999672397906286),
 (414, 0.999672397906286),
 (532, 0.999672397906286),
 (572, 0.999672397906286),
 (31, 0.9996557726314451),
 (29, 0.9996390766037325),
 (74, 0.9996390766037325),
 (92, 0.9996390766037325),
 (127, 0.9996390766037325),
 (391, 0.9996390766037325),
 (569, 0.9996390766037325),
 (644, 0.9996390766037325),
 (69, 0.9996224529936666),
 (122, 0.9996224529936666),
 (212, 0.9996224529936666),
 (381, 0.9996224529936666),
 (386, 0.9996224529936666),
 (76, 0.9995891333558881),
 (83, 0.9995891333558881),
 (88, 0.9995891333558881),
 (171, 0.9995891333558881),
 (390, 0.9995891333558881),
 (451, 0.9995891333558881),
 (575, 0.9995891333558881),
 (639, 0.9995891333558881),
 (189, 0.9993894351951986),
 (192, 0.9993894351951986),
 (193, 0.9993894351951986),
 (199, 0.9993894351951986),
 (578, 0.9993894351951986),
 (579, 0.9993894351951986),
 (581, 0.9993894351951986),
 (584, 0.9993894351951986),
 (191, 0.9992564693310602),
 (576, 0.9992564693310602),
 (190, 0.9991898566739486),
 (196, 0.9991898566739486),
 (200, 0.9991898566739486),
 (582, 0.9990569970325699),
 (195, 0.998990397672725),
 (577, 0.998990397672725),
 (583, 0.998990397672725),
 (197, 0.9986584105427252),
 (574, 0.9985918377535417),
 (194, 0.9984592961133625),
 (573, 0.9984592961133625)]

In [30]:
df2 = df2.iloc[:,0:52]

In [31]:
df2['location'].value_counts()
df2['location'].value_counts().loc[lambda x : x>5]
df3 = df2[df2['location'].map(df2['location'].value_counts()) > 5]
df3['location'].nunique()

36

In [32]:
df3.shape

(605, 52)

In [33]:
df3['location'] = df3['location'].str.replace(', Bangalore', '')

C:\Users\adisa\AppData\Local\Temp\ipykernel_2684\2921896998.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['location'] = df3['location'].str.replace(', Bangalore', '')

In [34]:
col =['location']
for i in col:
    F=pd.get_dummies(df3[i]) 
    df3 = pd.concat([df3,F],axis=1)
    df3.drop(i,inplace = True, axis = 1)

In [115]:
df3.iloc[:,:].columns

Index(['Price_for_one', 'northindian', 'chinese', 'beverages', 'desserts',
       'biryani', 'southindian', 'fastfood', 'streetfood', 'mughlai',
       'sichuan', 'shake', 'icecream', 'seafood', 'rolls', 'pizza', 'burger',
       'bakery', 'kebab', 'andhra', 'sandwich', 'juices', 'momos', 'arabian',
       'italian', 'kerala', 'mithai', 'asian', 'thai', 'continental',
       'lebanese', 'hyderabadi', 'pasta', 'healthyfood', 'salad', 'wraps',
       'cafe', 'bengali', 'mangalorean', 'mexican', 'waffle', 'japanese',
       'bbq', 'tea', 'rajasthani', 'coffee', 'sushi', 'american', 'chettinad',
       'oriental', 'tibetan', 'BTM', 'Banashankari', 'Basavanagudi',
       'Basaveshwara Nagar', 'Brigade Road', 'Church Street',
       'Cunningham Road', 'Domlur', 'Frazer Town', 'HBR Layout', 'Indiranagar',
       'Jayanagar', 'Jeevan Bhima Nagar', 'Kammanahalli',
       'Koramangala 5th Block', 'Koramangala 6th Block',
       'Koramangala 7th Block', 'Koramangala 8th Block', 'Lavelle Road',
       'MG Road', 'Majestic', 'Malleshwaram', 'Old Airport Road', 'RT Nagar',
       'Rajajinagar', 'Residency Road', 'Richmond Road', 'Seshadripuram',
       'Shanti Nagar', 'Shivajinagar', 'St. Marks Road', 'Thippasandra',
       'Ulsoor', 'Vasanth Nagar', 'Vijay Nagar', 'Wilson Garden'],
      dtype='object')

In [35]:
X=df3.drop(['Price_for_one'],axis=1) 
Y = df3['Price_for_one']

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [37]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.25,random_state=4)

In [38]:
X_train

,northindian,chinese,beverages,desserts,biryani,southindian,fastfood,streetfood,mughlai,sichuan,...,Richmond Road,Seshadripuram,Shanti Nagar,Shivajinagar,St. Marks Road,Thippasandra,Ulsoor,Vasanth Nagar,Vijay Nagar,Wilson Garden
232,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
68,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,1,0,0,0,0
278,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
163,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
413,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
501,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
193,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
134,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
X_test.shape

(152, 86)

In [40]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()

In [41]:
X_train=sc.fit_transform(X_train)

In [42]:
X_train

array([[-0.8772293 ,  1.15544431, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [ 1.1399528 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       ...,
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584],
       [-0.8772293 , -0.86546794, -0.79340809, ..., -0.10564428,
        -0.16495722, -0.09438584]])

In [43]:
X_test=sc.transform(X_test)

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
reg=LinearRegression()

In [46]:
reg.fit(X_train,Y_train)

LinearRegression()

In [47]:
Y_pred=reg.predict(X_test)

In [48]:
from sklearn import metrics

In [49]:
R2=metrics.r2_score(Y_test, Y_pred) 
R2

-0.27422510178804393

In [50]:
MSE=metrics.mean_squared_error(Y_test, Y_pred) 
MSE

9288.513074809032

In [51]:
RMSE=np.sqrt(MSE) 
RMSE

96.37693227535847

In [52]:
cusins=['northindian', 'chinese', 'beverages', 'desserts',
       'biryani', 'southindian', 'fastfood', 'streetfood', 'mughlai',
       'sichuan', 'shake', 'icecream', 'seafood', 'rolls', 'pizza', 'burger',
       'bakery', 'kebab', 'andhra', 'sandwich', 'juices', 'momos', 'arabian',
       'italian', 'kerala', 'mithai', 'asian', 'thai', 'continental',
       'lebanese', 'hyderabadi', 'pasta', 'healthyfood', 'salad', 'wraps',
       'cafe', 'bengali', 'mangalorean', 'mexican', 'waffle', 'japanese',
       'bbq', 'tea', 'rajasthani', 'coffee', 'sushi', 'american', 'chettinad',
       'oriental', 'tibetan']
location=['BTM', 'Banashankari', 'Basavanagudi', 'Basaveshwara Nagar',
       'Brigade Road', 'Church Street', 'Cunningham Road', 'Domlur',
       'Frazer Town', 'HBR Layout', 'Indiranagar', 'Jayanagar',
       'Jeevan Bhima Nagar', 'Kammanahalli', 'Koramangala 5th Block',
       'Koramangala 6th Block', 'Koramangala 7th Block',
       'Koramangala 8th Block', 'Lavelle Road', 'MG Road', 'Majestic',
       'Malleshwaram', 'Old Airport Road', 'RT Nagar', 'Rajajinagar',
       'Residency Road', 'Richmond Road', 'Seshadripuram', 'Shanti Nagar',
       'Shivajinagar', 'St. Marks Road', 'Thippasandra', 'Ulsoor',
       'Vasanth Nagar', 'Vijay Nagar', 'Wilson Garden']
final=cusins+location

In [55]:
cu1 ='northindian'.lower().replace(' ','')
cu2 = ''.lower().replace(' ','')
cu3 =''.lower().replace(' ','')
cu4 = ''.lower().replace(' ','')
cu5 = ''.lower().replace(' ','')

# North Indian, Continental, BBQ, Desserts, Beverages
# Mexican, Tex-Mex, Beverages
# Italian, Fast Food, Pasta, Pizza, Beverages, Desserts
count = 0
locat = 'whitefield'.title()
L = []
for i in final:
    if (cu1 == i) or (locat == i) or (cu2 == i) or (cu3==i)  or (cu4 == i) or (cu5 == i ):
        L.append(1)
        count += 1
    else:
        L.append(0)

L=[L]
A = sc.transform(L)
print(count)
if count == 0:
    print('error')
else:
    num = reg.predict(L)[0]
    print(int(round(num)))

1
192

C:\Users\adisa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(